# Site settings
title: grempe.github.io
email: glenn@rempe.us
description: > # this means to ignore newlines until "baseurl:"
  Glenn Rempe's personal website. It may not be much, but its all mine.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://grempe.github.io" # the base hostname & protocol for your site
twitter_username: grempe
github_username:  grempe

# Build settings
markdown: kramdown
