# Site settings
title: rempe.us
name: "Glenn Rempe"
email: glenn@rempe.us
description: > # this means to ignore newlines until "baseurl:"
  My personal website. It may not be much, but its all mine.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.rempe.us" # the base hostname & protocol for your site
source_url: "https://github.com/grempe/grempe.github.io" # the location of the source code for this site.
twitter_username: grempe
github_username:  grempe

# Build settings
markdown: kramdown
