# Site settings
theme: minima
timezone: "America/Los_Angeles"
title: rempe.us
name: "Glenn Rempe"
email: glenn@rempe.us
email_secure: grempe@pm.me
description: > # this means to ignore newlines until "baseurl:"
  A personal website for Glenn Rempe. All opinions expressed are my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.rempe.us" # the base hostname & protocol for your site with no trailing slash
source_url: "https://github.com/grempe/grempe.github.io" # the location of the source code for this site.
twitter_username: grempe
github_username:  grempe
linkedin_username: grempe
keybase_username: grempe

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# store static markdown pages in _pages/
include: ['_pages']
relative_permalinks: false

paginate:      5
permalink:     "/blog/:title/"
paginate_path: "/blog/page:num/"

# excerpt separator : insert in post content to split out first
# paragraph of content for index.html excerpt. First paragraph by default.
# http://jekyllrb.com/docs/posts/
#excerpt_separator: <!--more-->

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions

jekyll-mentions:
  base_url: https://twitter.com

# SEO
twitter:
  username: grempe
